# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fff5425a1955fd750e93c16fecafa992190c86c37b71862f5fe34e8a517401c534e0cdec3960a5ef7ebdad4b5932eb9b70384a222d91fff5722d588ed5402d80

test:
  secret_key_base: 35311239cf40bafc079844605efe5d080a65ed19e787d1f9618f39de56ef0c9ca9ae02f2a60dadb99a9366ad1a9081b0363187f01da75800f9da8d50f481dc9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
